### ISSUE TITLE
META: libpmemobj 1.7 release

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#1058]
- Performance Improvements
  - [p] Allocator transient state improvements pmem/pmdk#3642
  - [p] ulog invalidation instead of data clobbering #935
  - [x] asynchronous RDMA replica writes (flush/drain model) #870 
- Functionality
  - [ ] Expanded Actions API #880 
  - [ ] More allocator/transaction statistics #888 
  - [ ] allocation classes delete operation #936
  - [ ] transaction undo/redo log preallocation
- Tools / Benchmarks / Tests
  - [ ] new build system in CMake (stretch)
