### ISSUE TITLE
META: PMDK 1.8 release

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#1133]
- New library:
  - [ ] libpmem2 with more flexible API
- Functionality
  - [ ] Application-assisted defragmentation #927
  - [ ] Intent API (part 1) #880
  - [ ] optional transaction abort #1066

**Comment by kilobyte** [comment]
Should we include thread-safe pool opens/closes?  The bulk of the work is done, a test (currently failing) is in https://github.com/pmem/pmdk/pull/3846, the currently known culprit (which may or may not be the only problem) is re-parsing the config on each open, writing that to global variables (#1114).
