### ISSUE TITLE
A list of bug fixes to be backported to 1.3.2

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#774]
- [x] Missing -lpthread for some library links <https://github.com/pmem/issues/issues/767>
https://github.com/pmem/pmdk/pull/2558
- [x] redhat-rpm-config linker flags not injected into build <https://github.com/pmem/issues/issues/768>
https://github.com/pmem/pmdk/pull/2570
- [x] pmdk's builds started to fail in Fedora rawhide <https://github.com/pmem/issues/issues/773>
https://github.com/pmem/pmdk/pull/2578
- [x] PMDK does not compile with clang-5.0 <https://github.com/pmem/issues/issues/783>
https://github.com/pmem/pmdk/pull/2599
