### ISSUE TITLE
META: libpmemobj 1.5 release

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#869]
This is a meta issue for all significant features that we plan on shipping for the next release of libpmemobj.

- Performance Improvements
    - [x] Hybrid Transactions pmem/pmdk#2716
    - [x] Checksums for undo log snapshots #905
    - [x] Allocator transient state improvements
        - [x] Relaxed locking and faster bitmap parsing pmem/pmdk#2884
        - [ ] ~~Run tracking improvements #906~~
    - [ ] ~~asynchronous RDMA replica writes (flush/drain model) #870~~
- Under the hood changes
  - [x] Unified small/large undo logs #879
  - [x] Generalization of the current redo log to support undo type actions #889
  - [ ] ~~Simplified lane and recovery mechanism #890~~
  - [ ] ~~New multiple consumer single producer hashmap #871~~
- Functionality
  - [x] flexible pmemobj_mem[cpy|set|move] pmem/pmdk#2769
  - [ ] ~~Expanded Actions API #880~~
  - [x] Lazily initialized volatile variables pmem/pmdk#2624
  - [x] Aligned allocations pmem/pmdk#2654
  - [ ] ~~More allocator/transaction statistics #888~~
  - [ ] ~~thread-safe `pmemobj_create()`, `pmemobj_open()`, `pmemobj_close()` #872~~
  - [x] Lifting the limit of units per run #877
- RAS (Reliability, Availability and Serviceability)
  - [x] Unsafe Shutdown Count enabling
  - [x] Redo-style pmempool sync pmem/pmdk#2957
- Tools / Benchmarks
  - [x] new universal pool convert tool #907
  - [ ] ~~Fragmentation and long-term stability focused benchmarks #886~~
  - [x] valgrind pmemcheck store logging and reordering pmem/pmdk#2964
- Documentation / Examples
  - [ ] ~~Technical paper describing the library in detail #887~~
- C++
  - [x] pmem::obj::v pmem/pmdk#2624
  - [ ] ~~Change atomic make persistent to allow nesting #909~~
  - [x] Function names cleanup #908
  - [ ] Persistent Containers #910
    - [x] pmem::obj::array
    - [ ] ~~pmem::obj::vector~~

This is a living document, feel free to suggest new things.

**Comment by wmpeng** [comment]
According to your estimate, when will the 1.5 version be released?

**Comment by pbalcer** [comment]
Current plan is to release the new version around October.

**Comment by wmpeng** [comment]
Got it, thanks.

**Comment by pbalcer** [comment]
As we approach 1.5, the reality forced us to slightly reduce the scope of the release. All of the important performance improvements made it through, but we weren't able to deliver on one runtime scalability improvement - it will ship with the next release.
There were two other things we missed: threadsafe pool management, which is a relatively small ease of use improvement, but a difficult thing to implement, and we were only able to implement one C++ container, the array - the C++ work was always a stretch goal anyway, and we unfortunately encountered many difficulties with settling on intuitive and easy to use semantics for the new containers - it's not as easy as just copying the behavior of the standard classes ;)

**Comment by pbalcer** [comment]
Closing this issue because 1.5 has been released.
